services:
  - type: web
    name: btc-price-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    runtime: python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    autoDeploy: true
    branch: main
